#########################################
# Copyright (C) 2016 Project Bonfire    #
#                                       #
# This file is automatically generated! #
#             DO NOT EDIT!              #
#########################################

vlib work

# Include files and compile them


vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/gen/TB_Package.vhd"

vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/FIFO.vhd"
vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/LBDR.vhd"
vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/XBAR.vhd"
vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/ARBITER.vhd"
vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/Router/Router_v0_sim.vhd"

vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/gen/network_2x2.vhd"
vcom "/home/tsotne/ownCloud/git/EHA_ft/RTL/gen/tb_network_2x2.vhd"






# Start the simulation
vsim work.tb_network_2x2

# Draw waves
do wave_or.do
# Run the simulation
run 11000 ns
